name: Multi-Stage ML Pipeline

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  # 🔹 JOB 1: TRAIN
  train:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 🐍 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: 📦 Install deps
      run: pip install -r requirements.txt

    - name: 🚀 Train model
      run: python train.py

    - name: 📦 Upload model
      uses: actions/upload-artifact@v4
      with:
        name: model
        path: model.txt


  # 🔹 JOB 2: EVALUATE
  evaluate:
    needs: train   # 👈 depends on train job
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 🐍 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: 📦 Install deps
      run: pip install -r requirements.txt

    - name: 📥 Download model
      uses: actions/download-artifact@v4
      with:
        name: model

    - name: 📊 Evaluate
      run: python evaluate.py


  # 🔹 JOB 3: DEPLOY
  deploy:
    needs: evaluate   # 👈 only runs if evaluate SUCCESS
    runs-on: ubuntu-latest

    steps:
    - name: 🚀 Deploy model
      run: echo "Deploying model..."
