name: MLflow MLOps Pipeline

on:
  push:
    branches: ["main"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  MLFLOW_TRACKING_URI: https://iron-swinging-fall.ngrok-free.dev
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:

  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: 🔍 Debug AWS
        run: |
          echo "Region: $AWS_DEFAULT_REGION"
          python -c "import boto3; print('Region from boto3:', boto3.session.Session().region_name)"

      - name: 🔍 Test S3 access
        run: |
          python -c "import boto3; s3=boto3.client('s3'); print([b['Name'] for b in s3.list_buckets()['Buckets']])"

      - name: Train
        run: python train.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: model.txt


  evaluate:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: model

      - name: Evaluate
        run: python evaluate.py


  deploy:
    needs: evaluate
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploying model..."
